type Questions = {
  [id: string]: {
    value: any;
    type?: string;
    label: string;
    helperText?: string;
    options?: string[];
  };
};

const nationalities = [
  "Hong Kong",
  "Japan",
  "Macao",
  "Switzerland",
  "Singapore",
  "Italy",
  "Spain",
  "Australia",
  "Channel Islands",
  "Iceland",
  "South Korea",
  "Israel",
  "Sweden",
  "France",
  "Martinique",
  "Malta",
  "Canada",
  "Norway",
  "Ireland",
  "New Zealand",
  "Greece",
  "Luxembourg",
  "Netherlands",
  "Guadeloupe",
  "Portugal",
  "Finland",
  "Belgium",
  "Austria",
  "Germany",
  "Slovenia",
  "United Kingdom",
  "Réunion",
  "Cyprus",
  "Denmark",
  "U.S. Virgin Islands",
  "Taiwan",
  "Costa Rica",
  "Chile",
  "Guam",
  "Qatar",
  "Puerto Rico",
  "French Guiana",
  "Maldives",
  "Mayotte",
  "Czech Republic (Czechia)",
  "Barbados",
  "Curaçao",
  "Lebanon",
  "Poland",
  "Estonia",
  "Cuba",
  "United States",
  "Panama",
  "Croatia",
  "Albania",
  "Oman",
  "United Arab Emirates",
  "Turkey",
  "Uruguay",
  "French Polynesia",
  "New Caledonia",
  "Slovakia",
  "Bosnia and Herzegovina",
  "Colombia",
  "Thailand",
  "Bahrain",
  "Ecuador",
  "Sri Lanka",
  "Algeria",
  "Antigua and Barbuda",
  "China",
  "Peru",
  "Morocco",
  "Montenegro",
  "Tunisia",
  "Iran",
  "Hungary",
  "Argentina",
  "Aruba",
  "Saint Lucia",
  "Malaysia",
  "Brazil",
  "Romania",
  "Serbia",
  "Lithuania",
  "Brunei",
  "North Macedonia",
  "Syria",
  "Honduras",
  "Kuwait",
  "Vietnam",
  "Latvia",
  "Saudi Arabia",
  "Armenia",
  "Mauritius",
  "Bulgaria",
  "Mexico",
  "Nicaragua",
  "Belarus",
  "Belize",
  "Guatemala",
  "Jordan",
  "Jamaica",
  "Dominican Republic",
  "State of Palestine",
  "Paraguay",
  "Bahamas",
  "Georgia",
  "Micronesia",
  "El Salvador",
  "Trinidad and Tobago",
  "Kazakhstan",
  "Samoa",
  "Seychelles",
  "Cabo Verde",
  "Bangladesh",
  "Libya",
  "Solomon Islands",
  "Azerbaijan",
  "Russia",
  "St. Vincent & Grenadines",
  "North Korea",
  "Bhutan",
  "Grenada",
  "Egypt",
  "Ukraine",
  "Bolivia",
  "Venezuela",
  "Indonesia",
  "Moldova",
  "Suriname",
  "Uzbekistan",
  "Kyrgyzstan",
  "Tajikistan",
  "Nepal",
  "Philippines",
  "Tonga",
  "Western Sahara",
  "Iraq",
  "Sao Tome & Principe",
  "Vanuatu",
  "Cambodia",
  "Mongolia",
  "India",
  "Guyana",
  "Timor-Leste",
  "Rwanda",
  "Botswana",
  "Kiribati",
  "Laos",
  "Senegal",
  "Turkmenistan",
  "Madagascar",
  "Fiji",
  "Djibouti",
  "Ethiopia",
  "Pakistan",
  "Myanmar",
  "Eritrea",
  "Kenya",
  "Gabon",
  "Yemen",
  "Tanzania",
  "Sudan",
  "Afghanistan",
  "Malawi",
  "Mauritania",
  "Papua New Guinea",
  "Congo",
  "Comoros",
  "Liberia",
  "Haiti",
  "Ghana",
  "South Africa",
  "Namibia",
  "Zambia",
  "Uganda",
  "Niger",
  "Gambia",
  "Burkina Faso",
  "Benin",
  "Burundi",
  "Guinea",
  "Angola",
  "Zimbabwe",
  "Togo",
  "Mozambique",
  "DR Congo",
  "Eswatini",
  "Mali",
  "Cameroon",
  "Equatorial Guinea",
  "Guinea-Bissau",
  "Côte d'Ivoire",
  "South Sudan",
  "Somalia",
  "Sierra Leone",
  "Nigeria",
  "Lesotho",
  "Chad",
  "Central African Republic",
];

export const questions: Questions = {
  name: { value: "name", label: "What's your name?" },
  birthday: {
    value: "birthday",
    type: "date",
    label: "When is your birthday?",
  },
  gender: {
    value: "gender",
    label: "What is your biological sex?",
    helperText: "This information is used to determine your life expectancy.",
    type: "select",
    options: ["male", "female"],
  },
  nationality: {
    value: "nationality",
    label: "What is your Country of Birth?",
    helperText:
      "This information is used to determine your life expectancy. If you prefer, you can enter the country where you’ve spent most of your life or that you feel most closely associated with.",
    type: "select",
    options: nationalities.sort(),
  },

  highSchoolFinishDate: {
    value: "highSchoolFinishDate",
    type: "date",
    label: "🎓 When did/will you finish High School?",
    helperText: "Phew, aren’t you glad that’s over?",
  },
  collegeFinishDate: {
    value: "collegeFinishDate",
    type: "date",
    label: "🎓 When did/will you finish College?",
  },
  gradSchoolFinishDate: {
    value: "gradSchoolFinishDate",
    type: "date",
    label:
      "🎓 When did/will you finish Graduate School or any other advanced degree?",
  },
  eldestChildBirthday: {
    value: "eldestChildBirthday",
    type: "date",
    label: "👶 When was/will your first/oldest child born?",
  },
  youngestChildBirthday: {
    value: "youngestChildBirthday",
    type: "date",
    label: "👶 When was/will your last/youngest child born?",
    helperText: "Skip this field if you only have one child.",
  },
  anniversary: {
    value: "anniversary",
    type: "date",
    label: "💕 Are you married or in a long-term relationship?",
    helperText:
      "Enter your wedding date or the date your relationship started, if you would like to include this on your calendar.",
  },
  careerStartDate: {
    value: "careerStartDate",
    type: "date",
    label: "When did/will you begin working or start your career?",
    helperText:
      "Enter a date feels most important to you. If you pride yourself in working since you were a teenager, enter that date. Or you can enter the date you’ve started your first career.",
  },
  businessStartDate: {
    value: "businessStartDate",
    type: "date",
    label: "🚀 When did/will you launch your business?",
  },
  retirementDate: {
    value: "retirementDate",
    type: "date",
    label: "🌄 When do you want to retire?",
  },
  milestone1: {
    value: "milestone1",
    type: "date",
    label: "My milestone",
  },
  milestone2: {
    value: "milestone2",
    type: "date",
    label: "My milestone",
  },
  milestone3: {
    value: "milestone3",
    type: "date",
    label: "My milestone",
  },
  email: {
    value: "email",
    type: "email",
    label:
      "You made it to the end! Enter your email and then click submit to see your Life in Weeks",
    helperText:
      "Don’t worry, we won’t spam you. We will send you a copy of your chart though!",
  },
};

export {};
